from baseblock import BaseObject
from opensearch_helper.dto import ScoreResult as ScoreResult, find_score_type as find_score_type

class ScoreTopHit(BaseObject):
    def __init__(self) -> None: ...
    def process(self, d_top_hit: dict) -> ScoreResult: ...
